# Generated by Django 5.1.1 on 2024-10-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0002_alter_address_addresstype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='addressType',
            field=models.CharField(choices=[('nhà riêng', 'Nhà riêng'), ('văn phòng', 'Văn phòng')], default='nhà riêng', max_length=20),
        ),
    ]
