# Generated by Django 5.1.1 on 2024-11-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0003_alter_address_addresstype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='addressType',
            field=models.CharField(choices=[('văn phòng', 'Văn phòng'), ('nhà riêng', 'Nhà riêng')], default='nhà riêng', max_length=20),
        ),
    ]
