# Generated by Django 5.1.3 on 2024-12-01 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_inventorylog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorylog',
            old_name='created_at',
            new_name='log_date',
        ),
        migrations.RenameField(
            model_name='inventorylog',
            old_name='change_quantity',
            new_name='quantity_change',
        ),
        migrations.RemoveField(
            model_name='inventorylog',
            name='remaining_quantity',
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
