# Generated by Django 5.1.1 on 2024-10-06 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_product_updated_at_product_decorationtype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='rating',
            new_name='ratings',
        ),
    ]
