# Generated by Django 5.1.1 on 2024-10-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ecoFriendlyLevel',
            field=models.FloatField(default=1.0),
        ),
    ]
