# Generated by Django 5.1.1 on 2024-11-14 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_product_ecofriendlylevel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
