# Generated by Django 5.1.3 on 2024-11-25 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='applications',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ecoFriendlyLevel',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material',
        ),
        migrations.RemoveField(
            model_name='product',
            name='style',
        ),
        migrations.AlterField(
            model_name='product',
            name='decorationType',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
