# Generated by Django 5.1.1 on 2024-10-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('trả', 'Trả'), ('thất bại', 'Thất bại')], max_length=255),
        ),
    ]
