# Generated by Django 5.1.1 on 2024-11-15 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('đang xử lý', 'Đang xử lý'), ('đang giao', 'Đang giao'), ('đã giao', 'Đã giao')], default='đang xử lý', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
