# Generated by Django 5.1.1 on 2024-11-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_delivery_status_alter_order_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Đang xử lý'), ('shipping', 'Đang giao'), ('delivered', 'Đã giao')], default='pending', max_length=255),
        ),
    ]
